### ISSUE TITLE
pstm_div conflicting return type declaration

### ISSUE THREAD

**Issue by kaidokert** [matrixssl/matrixssl#10]
Fairly obscure minor issue: 
pstm.h defines :
``extern int32_t pstm_div(psPool_t *pool,...``

pstm.c declares in one codepath:
``int pstm_div(psPool_t *pool, ..``
and
``int32_t pstm_div(psPool_t *pool,..``

return type should be int32_t in both cases.

**Comment by CarloWood** [comment]
Seems this was fixed in the current repository. I wonder why this report was never closed?

**Comment by kaidokert** [comment]
I'll close it then :)
