### ISSUE TITLE
Error when compiling the library

### ISSUE THREAD

**Issue by campeon91** [matrixssl/matrixssl#15]
Hi,

i just cloned a fresh copy from the matrixssl source code but when compiling the following error occurred

```
math/pstmnt.c: In function ‘pstmnt_square’:
math/pstmnt.c:857:26: error: ‘n’ undeclared (first use in this function)
math/pstmnt.c:857:26: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [math/pstmnt.o] Error 1
make[2]: Leaving directory `/home/user/Desktop/matrixssl/crypto'
make[1]: *** [release] Error 2
make[1]: Leaving directory `/home/user/Desktop/matrixssl/crypto'
make: *** [libs] Error 2
```

i have just executed the command "make libs"

**Comment by NealtheSE** [comment]
me too, i met the same error when compile for mips platform.
`void pstmnt_square( const uint32_t a[], uint32_t * restrict r, int sz)
{
    if (pstmnt_square_comba(a, r, sz))
    {
        return;
    }

    /* No square function, just use multiplier. */
    /*pstmnt_mult(a, a, r, n);*/   
  /* this fix the compile err, but no sure if there is any potential fault caused by it*/
    pstmnt_mult(a, a, r, sz);
}
`

**Comment by gitcnd** [comment]
Note to authors: you only see this bug show up when building on an unusual architecture (for me, it was ARM)

**Comment by CarloWood** [comment]
This seems to be fixed in the current source code. I wonder why this report wasn't closed?
