### ISSUE TITLE
fails to build on mac os/x: unknown type name 'size_t'

### ISSUE THREAD

**Issue by gitcnd** [matrixssl/matrixssl#21]
[cnd@mac Downloads]$ git clone https://github.com/matrixssl/matrixssl.git
Cloning into 'matrixssl'...
remote: Counting objects: 1687, done.
remote: Total 1687 (delta 0), reused 0 (delta 0), pack-reused 1687
Receiving objects: 100% (1687/1687), 8.91 MiB | 827.00 KiB/s, done.
Resolving deltas: 100% (911/911), done.

[cnd@mac Downloads]$ cd matrixssl

[cnd@mac matrixssl]$ dir
total 192
drwx------+ 1468 cnd  staff  46976  5 Mar 23:42 ../
-rw-r--r--     1 cnd  staff    184  5 Mar 23:43 .gitattributes
-rw-r--r--     1 cnd  staff    710  5 Mar 23:43 .gitignore
-rw-r--r--     1 cnd  staff    131  5 Mar 23:43 AUTHORS
-rw-r--r--     1 cnd  staff   1831  5 Mar 23:43 FILES
-rw-r--r--     1 cnd  staff   2047  5 Mar 23:43 INSTALL
-rw-r--r--     1 cnd  staff  18028  5 Mar 23:43 LICENSE
-rw-r--r--     1 cnd  staff   9453  5 Mar 23:43 Makefile
-rw-r--r--     1 cnd  staff   3128  5 Mar 23:43 README.html
-rw-r--r--     1 cnd  staff   2750  5 Mar 23:43 README.md
drwxr-xr-x     5 cnd  staff    160  5 Mar 23:43 apps/
-rw-r--r--     1 cnd  staff  12834  5 Mar 23:43 common.mk
drwxr-xr-x     8 cnd  staff    256  5 Mar 23:43 configs/
drwxr-xr-x    19 cnd  staff    608  5 Mar 23:43 core/
drwxr-xr-x    17 cnd  staff    544  5 Mar 23:43 crypto/
drwxr-xr-x    21 cnd  staff    672  5 Mar 23:43 doc/
drwxr-xr-x     6 cnd  staff    192  5 Mar 23:43 makefiles/
drwxr-xr-x    27 cnd  staff    864  5 Mar 23:43 matrixssl/
-rw-r--r--     1 cnd  staff   3133  5 Mar 23:43 pgp.asc
-rw-r--r--     1 cnd  staff   2362  5 Mar 23:43 readme.txt
-rw-r--r--     1 cnd  staff  10951  5 Mar 23:43 release_notes-3-9-5-open.html
drwxr-xr-x     9 cnd  staff    288  5 Mar 23:43 testkeys/
drwxr-xr-x     3 cnd  staff     96  5 Mar 23:43 thirdparty/
drwxr-xr-x    26 cnd  staff    832  5 Mar 23:43 ./
drwxr-xr-x    12 cnd  staff    384  5 Mar 23:43 xcode/
drwxr-xr-x    13 cnd  staff    416  5 Mar 23:43 .git/

[cnd@mac matrixssl]$ make
clang: error: unknown argument: '-print-multiarch'
clang: error: no input files
Compiling target architecture: x86_64-apple-darwin17.4.0
If this is incorrect, provide the CCARCH variable manually to make.
NOTE: Using default configuration from configs/default/coreConfig.h.
NOTE: Using default configuration from configs/default/cryptoConfig.h.
NOTE: Using default configuration from configs/default/matrixsslConfig.h.
/Applications/Xcode.app/Contents/Developer/usr/bin/make --directory=core
clang: error: unknown argument: '-print-multiarch'
clang: error: no input files
Compiling target architecture: x86_64-apple-darwin17.4.0
If this is incorrect, provide the CCARCH variable manually to make.
clang: error: unknown argument: '-print-multiarch'
clang: error: no input files
Compiling target architecture: x86_64-apple-darwin17.4.0
If this is incorrect, provide the CCARCH variable manually to make.
cc -O0 -g -fverbose-asm    -S memset_s.c
cc -O0 -Wall -ffunction-sections -fdata-sections -o memset_s.o  -m64  -c memset_s.c
cc            -O3 -Wall           -maes -ffunction-sections -fdata-sections -fomit-frame-pointer -Wno-error=unused-variable -Wno-error=#warnings -Wno-error=#pragma-messages -I.. -isystem -I/usr/include -m64               -c -o corelib.o corelib.c
In file included from corelib.c:35:
In file included from ./coreApi.h:47:
./osdep-types.h:295:9: error: unknown type name 'size_t'; did you mean 'psSize_t'?
typedef size_t psSizeL_t;
        ^~~~~~
        psSize_t
./osdep-types.h:287:18: note: 'psSize_t' declared here
typedef uint16_t psSize_t;
                 ^
1 error generated.
make[2]: *** [corelib.o] Error 1
make[1]: *** [release] Error 2
make: *** [libs] Error 2

[cnd@mac matrixssl]$

**Comment by gitcnd** [comment]
This problem can be fixed by adding this build flag:
    -fheinous-gnu-extensions

and doing this in all sources:
    :1,$s/size_t\|psSize_t/psSizeL_t/g

(i.e. change all size_t and psSize_t to psSizeL_t)

**Comment by matrixssl-admin** [comment]
This is no longer an issue in Mac builds. Unfortunately the test applications have other issues nowadays. We'll try to support MacOs better in the future.
