### ISSUE TITLE
mastrixSSL assert on invalid? packet

### ISSUE THREAD

**Issue by vonydev** [matrixssl/matrixssl#3]
Hello,

When processing these 2 packets an assertion is triggered:

Packet 1:

```
16030100960100009203031d126c1ec53d2b5319ee89d12e3fddeba39e61
34af27cb1b6e0d881d7aa8884b00001ac02fc02bc011c007c013c009c014
c00a0005002f0035c012000a0100004f0000001d001b000018646f6d6169
6e6e616d65646f6d61696e6e616d652e636f6d000500050100000000000a
00080006001700180019000b00020100000d000a00080401040302010203
ff01000100

>>> Server parsing CLIENT_HELLO
<<< Server creating SERVER_HELLO message
<<< Server creating CERTIFICATE  message
<<< Server creating CERTIFICATE_STATUS  message
<<< Server creating SERVER_KEY_EXCHANGE message
<<< Server creating SERVER_HELLO_DONE message
```

Packet2:

```
140303000101

>>> Server parsing CHANGE_CIPHER_SPEC message
Invalid CipherSpec order: 16
psAssert inc/matrixssl-3-8-4-open/matrixssl/sslDecode.c:1422 origbuf == *buf
Aborted (core dumped)
```

Let me know if I can be of any assistance,

**Comment by GrantEdwards** [comment]
With v3.8.6 I'm seeing similar psAssert failures during a Nessus network scan.

    psAssert sslDecode.c:1432: origbuf == *buf
    psAssert matrixsslApi.c:1008: prevBuf == buf
    psAssert matrixsslApi.c:1011: buf == ssl->inbuf
    ...
    psAssert sslDecode.c:1432: origbuf == *buf
    psAssert matrixsslApi.c:1008: prevBuf == buf
    psAssert matrixsslApi.c:1011: buf == ssl->inbuf

Has this problem every been addressed?

**Comment by matrixssl-admin** [comment]
I believe the 4.x series should behave better in such cases. Please reopen or open a new case if similar behaviour is found with a recent release.
