### ISSUE TITLE
DTLS server can be used as network traffic reflector/amplifier for DDoS attacks

### ISSUE THREAD

**Issue by cve-reporting** [matrixssl/matrixssl#31]
MatrixSSL DTLS server (in all publicly released versions including 4.2.1 OPEN) can be used to perform Distributed Denial of Service attacks as network amplifier with spoofing of the source IP address.

After receiving crafted DTLS message (63 bytes long) MatrixSSL DTLS server responds with 7 DTLS v1.2 packets:
- 6 x Hello Verify Request - 6 x 88 bytes,
- DTLS Alert (Level: Warning, Description: Close Notify) - 62 bytes.

Together all response packets are 590 bytes, which gives 836% amplification factor (calculated as: output/input - 1).
Server responds to IP address from first packet without getting any concurrent response from client, so this request can be used for Distributed Denial of Service.

Reproduction:

1. Download and compile MatrixSSL 4.2.1 OPEN (or earlier).
    
2. Run DTLS server:
    cd matrixssl-4-2-1-open
    apps/dtls/dtlsServer -p 44444

3. Run Wireshark (or other network sniffer) and observe incoming and outgoing traffic

4. Unzip and send attached crafted message e.g. using netcat:
    netcat -u $IP 44444 < payload_matrixssl_000.raw
    where $IP is IP of test server

[payload_matrixssl_000.raw.zip](https://github.com/matrixssl/matrixssl/files/3430998/payload_matrixssl_000.raw.zip)

**Comment by matrixssl-admin** [comment]
Fixed in 4.2.2.
