### ISSUE TITLE
Heap based buffer overread while parsing DTLS messages (parseSSLHandshake)

### ISSUE THREAD

**Issue by cve-reporting** [matrixssl/matrixssl#32]
MatrixSSL DTLS server (in all publicly released versions including 4.2.1 OPEN) incorrectly handles incoming network messages leading to heap-buffer overread with value provided in input packet (e.g. 1MB), leading to crash of the server.

Proposed CVSS 3.0 score:
7.5 (High) - CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H

Error message WITHOUT Address Sanitizer:
--------------------------------------------------------------------------------------
    ./matrixssl-4-2-1-open/apps/dtls/dtlsServer -p 44444
    DTLS server running on port 44444
    Select woke 1
    Aiee, segfault! You should probably report this as a bug to the developer
--------------------------------------------------------------------------------------

Error message WITH Address Sanitizer:
--------------------------------------------------------------------------------------
    ./matrixssl-ASAN/apps/dtls/dtlsServer -p 44444
    DTLS server running on port 44444
    sslBuf = 0x61b00001e380 recvfromBuf = 0x61b00001f180 recvLen = 67
    sslBuf = 0x61b00001ea80 recvfromBuf = 0x61b00001f180 recvLen = 1047
    =================================================================
        ==18755==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61b00001f05c at pc 0x7ff9fffc0935 bp 0x7fff8b956040 sp 0x7fff8b9557e8
        READ of size 1048576 at 0x61b00001f05c thread T0
            #0 0x7ff9fffc0934 in __asan_memcpy (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x8c934)
            #1 0x41ba32 in matrixSslDecode (matrixssl-ASAN/apps/dtls/dtlsServer+0x41ba32)
            #2 0x4130d2 in matrixSslReceivedData (matrixssl-ASAN/apps/dtls/dtlsServer+0x4130d2)
            #3 0x403c27 in main (matrixssl-ASAN/apps/dtls/dtlsServer+0x403c27)
            #4 0x7ff9ff96d82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
            #5 0x405308 in _start (matrixssl-ASAN/apps/dtls/dtlsServer+0x405308)

        0x61b00001f05c is located 0 bytes to the right of 1500-byte region [0x61b00001ea80,0x61b00001f05c)
        allocated by thread T0 here:
            #0 0x7ff9fffcc602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
            #1 0x40d098 in matrixSslNewSession (matrixssl-ASAN/apps/dtls/dtlsServer+0x40d098)

        SUMMARY: AddressSanitizer: heap-buffer-overflow ??:0 __asan_memcpy
        Shadow bytes around the buggy address:
          0x0c367fffbdb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
          0x0c367fffbdc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
          0x0c367fffbdd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
          0x0c367fffbde0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
          0x0c367fffbdf0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        =>0x0c367fffbe00: 00 00 00 00 00 00 00 00 00 00 00[04]fa fa fa fa
          0x0c367fffbe10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
          0x0c367fffbe20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
          0x0c367fffbe30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
          0x0c367fffbe40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
          0x0c367fffbe50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        Shadow byte legend (one shadow byte represents 8 application bytes):
          Addressable:           00
          Partially addressable: 01 02 03 04 05 06 07 
          Heap left redzone:       fa
          Heap right redzone:      fb
          Freed heap region:       fd
          Stack left redzone:      f1
          Stack mid redzone:       f2
          Stack right redzone:     f3
          Stack partial redzone:   f4
          Stack after return:      f5
          Stack use after scope:   f8
          Global redzone:          f9
          Global init order:       f6
          Poisoned by user:        f7
          Container overflow:      fc
          Array cookie:            ac
          Intra object redzone:    bb
          ASan internal:           fe
        ==18755==ABORTING
--------------------------------------------------------------------------------------

Reproduction:

1. Download and compile MatrixSSL 4.2.1 OPEN (or earlier).
    
2. Run DTLS server:
    cd matrixssl-4-2-1-open
    apps/dtls/dtlsServer -p 44444

3. Unzip and send attached crafted message e.g. using netcat:
    netcat -u $IP 44444 < payload_matrixssl_002.raw
    where $IP is IP of test server

[payload_matrixssl_002.raw.zip](https://github.com/matrixssl/matrixssl/files/3431024/payload_matrixssl_002.raw.zip)

**Comment by matrixssl-admin** [comment]
Should be fixed in 4.2.2
