### ISSUE TITLE
MatrixSSL 4.6 announcement.

### ISSUE THREAD

**Issue by matrixssl-admin** [matrixssl/matrixssl#47]
Hello,
The MatrixSSL team at Rambus is announcing the upcoming security-fix release of MatrixSSL version 4.6.

This release will be made available on Thursday, December 29th 2022, between 10:00-14:00 UTC.
MatrixSSL 4.6 is a security-fix release. The severity level of the issue fixed in this release is CRITICAL.

Best Regards,
MatrixSSL Team

**Comment by m-terlinde** [comment]
Would it be possible to publish a security advisory to better understand the impact?

**Comment by matrixssl-admin** [comment]
> Would it be possible to publish a security advisory to better understand the impact?

Yes it would. We were kind of waiting for the CVE to become public, but decided to publish one now. We will update the advisory as needed.
